<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEdMd8Rq\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEdMd8Rq/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerEdMd8Rq.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerEdMd8Rq\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerEdMd8Rq\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'EdMd8Rq',
    'container.build_id' => 'ef84de46',
    'container.build_time' => 1524482691,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerEdMd8Rq');
